export enum EnviromentVariablesEnum {
    PORT = 'PORT',
    ENABLE_CORS = 'ENABLE_CORS',
    ENABLE_DOCS = 'ENABLE_DOCS',

    DB_CONNECTION_STRING = 'DB_CONNECTION_STRING',
    DB_PORT = 'DB_PORT',
    DB_NAME = 'DB_NAME',
    DB_USER = 'DB_USER',
    DB_PASSWORD = 'DB_PASSWORD',
    DB_SYNCHRONIZE = 'DB_SYNCHRONIZE',

    JWT_KEY = 'JWT_KEY',
    JWT_EXPIRATION = 'JWT_EXPIRATION',

    JWT_KEY_BACKOFFICE = 'JWT_KEY_BACKOFFICE',

    AWS_REGION = 'AWS_REGION',
    AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
    AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',

    S3_BUCKET_USER_PHOTO = 'S3_BUCKET_USER_PHOTO',

    S3_BUCKET_DOCUMENTS = 'S3_BUCKET_DOCUMENTS',

    ZENVIA_TOKEN = 'ZENVIA_TOKEN',
    ZENVIA_EMAIL = 'ZENVIA_EMAIL',

    SENDGRID_API_KEY = 'SENDGRID_API_KEY',
    SENDGRID_EMAIL_SENDER = 'SENDGRID_EMAIL_SENDER',

    GOOGLE_API_KEY = 'GOOGLE_API_KEY',

    CEP_API = 'CEP_API',

    PHOTO_SCHEDULE_KM_LIMIT = 'PHOTO_SCHEDULE_KM_LIMIT',
    INSPECTOR_SCHEDULE_KM_LIMIT = 'INSPECTOR_SCHEDULE_KM_LIMIT',

    S3_BUCKET_ANNOUNCEMENT_PHOTO = 'S3_BUCKET_ANNOUNCEMENT_PHOTO',
}